In [1]:
import pandas as pd

In [2]:
dfMovies=pd.read_csv(r'D:\Nagesh\DataScience\ClassNotes\6th\movie.csv')
dfMovies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [3]:
dfMovies['year'] = dfMovies['title'].str.extract('.*\((.*)\).*', expand=True)
dfMovies

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995
...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,2007
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,2002
27275,131258,The Pirates (2014),Adventure,2014
27276,131260,Rentun Ruusu (2001),(no genres listed),2001
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,2014

In [4]:
dfMovies['Name']=dfMovies['title'].str[:-6]
dfMovies

,movieId,title,genres,year,Name
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,Toy Story
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995,Jumanji
2,3,Grumpier Old Men (1995),Comedy|Romance,1995,Grumpier Old Men
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,Waiting to Exhale
4,5,Father of the Bride Part II (1995),Comedy,1995,Father of the Bride Part II
...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,2007,Kein Bund für's Leben
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,2002,"Feuer, Eis & Dosenbier"
27275,131258,The Pirates (2014),Adventure,2014,The Pirates
27276,131260,Rentun Ruusu (2001),(no genres listed),2001,Rentun Ruusu
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,2014,Innocence

In [5]:
movie_genres = dfMovies['genres'].str.split('|', expand=True)
movie_genres[:10]

,0,1,2,3,4,5,6,7,8,9
0,Adventure,Animation,Children,Comedy,Fantasy,None,None,None,None,None
1,Adventure,Children,Fantasy,None,None,None,None,None,None,None
2,Comedy,Romance,None,None,None,None,None,None,None,None
3,Comedy,Drama,Romance,None,None,None,None,None,None,None
4,Comedy,None,None,None,None,None,None,None,None,None
5,Action,Crime,Thriller,None,None,None,None,None,None,None
6,Comedy,Romance,None,None,None,None,None,None,None,None
7,Adventure,Children,None,None,None,None,None,None,None,None
8,Action,None,None,None,None,None,None,None,None,None
9,Action,Adventure,Thriller,None,None,None,None,None,None,None

In [6]:
dfMovies['isAdventure']=dfMovies['genres'].str.contains('Adventure')
dfMovies

,movieId,title,genres,year,Name,isAdventure
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,Toy Story,True
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995,Jumanji,True
2,3,Grumpier Old Men (1995),Comedy|Romance,1995,Grumpier Old Men,False
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,Waiting to Exhale,False
4,5,Father of the Bride Part II (1995),Comedy,1995,Father of the Bride Part II,False
...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,2007,Kein Bund für's Leben,False
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,2002,"Feuer, Eis & Dosenbier",False
27275,131258,The Pirates (2014),Adventure,2014,The Pirates,True
27276,131260,Rentun Ruusu (2001),(no genres listed),2001,Rentun Ruusu,False
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,2014,Innocence,True

In [7]:
dfMovies['isAnimation']=dfMovies['genres'].str.contains('Animation')
dfMovies['isChildren']=dfMovies['genres'].str.contains('Children')
dfMovies['isComedy']=dfMovies['genres'].str.contains('Comedy')
dfMovies['isFantasy']=dfMovies['genres'].str.contains('Fantasy')
dfMovies['isHorror']=dfMovies['genres'].str.contains('Horror')
dfMovies['isThriller']=dfMovies['genres'].str.contains('Thriller')
dfMovies['isRomance']=dfMovies['genres'].str.contains('Romance')
dfMovies['isDrama']=dfMovies['genres'].str.contains('Drama')
dfMovies['isCrime']=dfMovies['genres'].str.contains('Crime')
dfMovies

,movieId,title,genres,year,Name,isAdventure,isAnimation,isChildren,isComedy,isFantasy,isHorror,isThriller,isRomance,isDrama,isCrime
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,Toy Story,True,True,True,True,True,False,False,False,False,False
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995,Jumanji,True,False,True,False,True,False,False,False,False,False
2,3,Grumpier Old Men (1995),Comedy|Romance,1995,Grumpier Old Men,False,False,False,True,False,False,False,True,False,False
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,Waiting to Exhale,False,False,False,True,False,False,False,True,True,False
4,5,Father of the Bride Part II (1995),Comedy,1995,Father of the Bride Part II,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,2007,Kein Bund für's Leben,False,False,False,True,False,False,False,False,False,False
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,2002,"Feuer, Eis & Dosenbier",False,False,False,True,False,False,False,False,False,False
27275,131258,The Pirates (2014),Adventure,2014,The Pirates,True,False,False,False,False,False,False,False,False,False
27276,131260,Rentun Ruusu (2001),(no genres listed),2001,Rentun Ruusu,False,False,False,False,False,False,False,False,False,False
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,2014,Innocence,True,False,False,False,True,True,False,False,False,False

In [8]:
new1=dfMovies[['movieId','Name','year','isAdventure','isAnimation','isChildren','isComedy','isFantasy','isHorror','isThriller','isRomance','isDrama','isCrime']]
new1

,movieId,Name,year,isAdventure,isAnimation,isChildren,isComedy,isFantasy,isHorror,isThriller,isRomance,isDrama,isCrime
0,1,Toy Story,1995,True,True,True,True,True,False,False,False,False,False
1,2,Jumanji,1995,True,False,True,False,True,False,False,False,False,False
2,3,Grumpier Old Men,1995,False,False,False,True,False,False,False,True,False,False
3,4,Waiting to Exhale,1995,False,False,False,True,False,False,False,True,True,False
4,5,Father of the Bride Part II,1995,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben,2007,False,False,False,True,False,False,False,False,False,False
27274,131256,"Feuer, Eis & Dosenbier",2002,False,False,False,True,False,False,False,False,False,False
27275,131258,The Pirates,2014,True,False,False,False,False,False,False,False,False,False
27276,131260,Rentun Ruusu,2001,False,False,False,False,False,False,False,False,False,False
27277,131262,Innocence,2014,True,False,False,False,True,True,False,False,False,False